version: "3"
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config.json:/freqtrade/config.json:ro
      - ./lighter-wasm:/freqtrade/lighter-wasm:ro
    ports:
      - "127.0.0.1:8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/config.json
      --strategy SampleStrategy
    environment:
      - TZ=America/Denver
