#!/bin/bash
# mem-profile.sh — Generate condensed user profile from MEMORY.md
# Output: memory/profile.md
set -euo pipefail

W="/root/.openclaw/workspace"
source "$W/.env" 2>/dev/null || true
[ -z "${OPENROUTER_API_KEY:-}" ] && echo "⚠️ No API key" && exit 1

MEMORY_FILE="$W/MEMORY.md"
PROFILE_FILE="$W/memory/profile.md"

CURRENT=$(cat "$MEMORY_FILE" 2>/dev/null || echo "")
[ -z "$CURRENT" ] && echo "⚠️ No MEMORY.md found" && exit 1

PROMPT=$(cat << 'PROMPT_EOF'
You are a profile distiller. Read this MEMORY.md and extract a CONDENSED USER PROFILE.

The profile should be a quick reference for an AI assistant starting a new conversation.
It should answer: "Who is this person and how should I interact with them?"

## MEMORY.md Content:
{{MEMORY}}

## Output format (markdown):
# User Profile

**Name:** ...
**Timezone:** ...
**Vibe:** 1-2 sentence personality summary

## Active Projects
- bullet list (max 5)

## Key Preferences
- top 3-4 preferences

## How to Behave
- 3-4 behavioral rules that matter most

## Things to Remember
- key personal details, emotional context, important relationships
- things that would hurt if forgotten

## ⚠️ Red Lines
- the absolute don'ts

## Philosophy (brief)
- 1-2 sentence summary of their worldview

Rules:
- MAX 200 words total. This must be scannable in 5 seconds.
- Only include things that would change how you interact.
- Skip infrastructure details (server, model, gateway versions).
- Emotional weight matters — include what would hurt to forget.
PROMPT_EOF
)

PROMPT="${PROMPT//\{\{MEMORY\}\}/$CURRENT}"

RESULT=$(echo "$PROMPT" | bash "$W/scripts/memory-llm.sh" \
  "You are a profile distiller. Be concise, warm, and practical." \
  "google/gemini-2.5-flash" 2048 2>/dev/null) || true

if [ -z "$RESULT" ] || echo "$RESULT" | grep -q '"error"'; then
  echo "⚠️ Profile generation failed"
  exit 1
fi

{
  echo "<!-- Auto-generated by mem-profile.sh. Do not edit manually. -->"
  echo "<!-- Regenerated: $(date -u '+%Y-%m-%d %H:%M UTC') -->"
  echo ""
  echo "$RESULT"
} > "$PROFILE_FILE"

WORDS=$(echo "$RESULT" | wc -w)
echo "✅ Profile generated: $PROFILE_FILE ($WORDS words)"
